apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.backendReport.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.backendReport.image }}
        ports:
            - containerPort:{{ .Values.backendReport.port }}
        
        envFrom:
            - configMapRef:
              name: {{ .Chart.Name }}-config
            - secretRef:
              name: {{ .Chart.Name }}-secret
        
        strategy:
          {{ toYaml Values.backendReport.strategy | nindent 4}}

        resources:
          requests:
            cpu: {{ .Values.backendReport.resources.requests.cpu }}
            memory: {{ .Values.backendReport.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backendReport.resources.limits.cpu }}
            memory: {{ .Values.backendReport.resources.limits.memory }}
