global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: YOUR_STUDENT_HOSTNAME.students-projects.ru
    path: /
    pathType: Prefix
  containerPort: 80
  image: iezek1il/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: iezek1il/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
  ### Опишите LivenessProbe для бэкенда
  vpa:
  ### Опишите VPA для бэкенда

backendReport:
  replicas: 2

  image: "iezek1il/backend-reporter:latest"

  port: "8080"

  db:
    url: "mongodb://mongo:27017/reports"

  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"

    limits:
      cpu: "1"
      memory: "512Mi"

    strategy:
      type: Recreate
### Опишите HPA для backend-report

infra:
  postgresql:
    env:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_PORT: 5432
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
