apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-vpa
    labels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
      app.kubernetes.io/managed-by: "{{ .Release.Service }}"
      helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      app.kubernetes.io/component: "{{ .Chart.Name }}"
      app.kubernetes.io/part-of: "sausage-store"
      env: "{{ .Values.global.environment }}"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "{{ .Chart.Name }}"
      minAllowed:
        cpu: {{ .Values.vpa.containerPolicies.minAllowed.cpu }}
        memory: {{ .Values.vpa.containerPolicies.minAllowed.memory }}
      maxAllowed:
        cpu: {{ .Values.vpa.containerPolicies.maxAllowed.cpu }}
        memory: {{ .Values.vpa.containerPolicies.maxAllowed.memory }}
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
